"""Event types and tactical adjustment enums for match simulation.

This file defines the framework for events and tactical adjustments.
The actual event content is generated by LLM calls during the match.
"""
from models import EventType, EventSubtype, TacticalAdjustmentType

# ─── Event framework ──────────────────────────────────────────────────

# Possible event types the LLM can choose from
POSSIBLE_EVENT_TYPES = [
    EventType.SHOT,
    EventType.GOAL,
    EventType.FOUL,
    EventType.CORNER,
    EventType.OFFSIDE,
    EventType.CARD,
    EventType.SUBSTITUTION,
    EventType.INJURY,
    EventType.SAVE,
    EventType.PENALTY,
    EventType.FREE_KICK,
    EventType.THROW_IN,
    EventType.GOAL_KICK,
    EventType.PASSAGE_OF_PLAY,
]

# Event constraints for LLM guidance
EVENT_CONSTRAINTS = {
    EventType.GOAL: "Must follow a shot event or penalty. Cannot happen more than once per 3 minutes on average.",
    EventType.CARD: "Yellow cards spread across match. Red card max 1 per match. Usually for tactical fouls or dangerous play.",
    EventType.SUBSTITUTION: "Max 5 per team per match. Typically after minute 55. First subs usually around minute 60-70.",
    EventType.PENALTY: "Rare (1-2 per match max). Must include foul in box context.",
    EventType.INJURY: "Player may need to be substituted. More common in second half.",
}

# ─── Tactical adjustment framework ─────────────────────────────────────

# NOTE: cooldown=0 表示无冷却，用户和 AI 可随时连续调整。
USER_TACTICAL_ADJUSTMENTS = {
    TacticalAdjustmentType.SUBSTITUTION:       {"label": "换人",       "cooldown": 0, "description": "替换场上球员，最多5次换人机会"},
    TacticalAdjustmentType.FORMATION_CHANGE:   {"label": "变阵",       "cooldown": 0, "description": "改变球队阵型（如 4-3-3 → 4-4-2）"},
    TacticalAdjustmentType.ATTACK_BOOST:       {"label": "加强进攻",   "cooldown": 0, "description": "显著提高进攻威胁，但会增加被反击风险"},
    TacticalAdjustmentType.DEFENSE_BOOST:      {"label": "加强防守",   "cooldown": 0, "description": "提高防守效率，但会略微降低进攻投入"},
    TacticalAdjustmentType.POSSESSION_FOCUS:   {"label": "控制球权",   "cooldown": 0, "description": "放慢节奏，传控为主"},
    TacticalAdjustmentType.COUNTER_ATTACK:     {"label": "防守反击",   "cooldown": 0, "description": "同时增强防守稳定性和快速转换威胁"},
    TacticalAdjustmentType.HIGH_PRESS:         {"label": "高位逼抢",   "cooldown": 0, "description": "在前场进行高强度压迫"},
    TacticalAdjustmentType.LOW_BLOCK:          {"label": "低位防守",   "cooldown": 0, "description": "明显增强防守并降低比赛节奏，牺牲进攻"},
    TacticalAdjustmentType.ALL_OUT_ATTACK:     {"label": "全力进攻",   "cooldown": 0, "description": "放弃防守，全员压上进攻（仅落后时可用）"},
    TacticalAdjustmentType.TIME_WASTING:       {"label": "拖延时间",   "cooldown": 0, "description": "控制节奏，消耗比赛时间（仅领先时可用）"},
}

AVAILABLE_FORMATIONS = [
    "4-3-3", "4-4-2", "3-5-2", "4-2-3-1",
    "3-4-3", "5-3-2", "4-1-4-1", "4-3-2-1",
]

# ─── Team formation helpers ────────────────────────────────────────────

# Position mapping for each formation (number of players per position group)
FORMATION_POSITIONS = {
    "4-3-3":    {"GK": 1, "CB": 2, "LB": 1, "RB": 1, "CM": 2, "CDM": 1, "LW": 1, "RW": 1, "ST": 1},
    "4-4-2":    {"GK": 1, "CB": 2, "LB": 1, "RB": 1, "CM": 2, "LM": 1, "RM": 1, "ST": 2},
    "3-5-2":    {"GK": 1, "CB": 3, "CM": 2, "CDM": 1, "LM": 1, "RM": 1, "ST": 2},
    "4-2-3-1":  {"GK": 1, "CB": 2, "LB": 1, "RB": 1, "CDM": 2, "CAM": 1, "LW": 1, "RW": 1, "ST": 1},
    "3-4-3":    {"GK": 1, "CB": 3, "CM": 2, "LM": 1, "RM": 1, "LW": 1, "RW": 1, "ST": 1},
    "5-3-2":    {"GK": 1, "CB": 3, "LB": 1, "RB": 1, "CM": 2, "CDM": 1, "ST": 2},
    "4-1-4-1":  {"GK": 1, "CB": 2, "LB": 1, "RB": 1, "CDM": 1, "CM": 2, "LM": 1, "RM": 1, "ST": 1},
    "4-3-2-1":  {"GK": 1, "CB": 2, "LB": 1, "RB": 1, "CM": 3, "CAM": 2, "ST": 1},
}


def get_positions_for_formation(formation: str) -> dict:
    """Get the position slots needed for a given formation."""
    return FORMATION_POSITIONS.get(formation, FORMATION_POSITIONS["4-3-3"])
